# defining the name of the workflow
name: Run Python Tests

# specifying this wokrflow will get triggered if we push anything to main branch
on:
  push:
    branches:
       - main

# specifying to build our project on ubuntu
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/checkout@v1
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: 
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
      
      - name: Run tests with pytest
        run: pytest test.py
